//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NChapman_Miller_lab_3_CPT206.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\StateInfo.mdf" +
            ";Integrated Security=True")]
        public string StateInfoConnectionString {
            get {
                return ((string)(this["StateInfoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=C:\\USERS\\THESH\\SOURCE\\REPOS\\NC" +
            "HAPMAN-MILLER-LAB-3-CPT206\\NCHAPMAN-MILLER-LAB-3-CPT206\\STATEINFO.MDF;Integrated" +
            " Security=True")]
        public string C__USERS_THESH_SOURCE_REPOS_NCHAPMAN_MILLER_LAB_3_CPT206_NCHAPMAN_MILLER_LAB_3_CPT206_STATEINFO_MDFConnectionString {
            get {
                return ((string)(this["C__USERS_THESH_SOURCE_REPOS_NCHAPMAN_MILLER_LAB_3_CPT206_NCHAPMAN_MILLER_LAB_3_CP" +
                    "T206_STATEINFO_MDFConnectionString"]));
            }
        }
    }
}
